const actionTypes = {
    UPDATE_IMAGES: "UPDATE IMAGES",
    UPDATE_VIDEOS: "UPDATE VIDEOS",
    UPDATE_SELECTED_IMAGE: "UPDATE SELECTED IMAGE",
    UPDATE_SELECTED_VIDEOS: "UPDATE SELECTED VIDEOS",
    DEL_IMAGE: "DELETE IMAGE",
    DEL_VIDEO: "DELETE_VIDEO",
}

export default actionTypes;